from .abstract_strategy import AbstractStrategy
from .buy_and_hold_strategy import BuyAndHold
from .random_investment_strategy import RandomInvestment
from .sequential_investment_strategy import SequentialInvestment
from .trend_following_strategy import TrendFollowing
from .trend_following_macd_strategy import TrendFollowingMACD
from .prediction_strategy import PredictionStrategy
